name: Deploy to Cloud Run Functions 2nd gen.
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # GCPに安全に認証するためのOIDC認証のIDトークン発行を許可

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          #GitHubのOIDCトークンを検証するためのGCP上の設定
          workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}" 
          service_account: "${{ secrets.SERVICE_ACCOUNT }}"

      - name: Configure Docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build & Push Docker Image
        run: |
          docker build -t asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-functions/my-app:${{ github.sha }} .
          docker push asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-functions/my-app:${{ github.sha }}

      - name: Deploy to Cloud Functions
        run: |
          gcloud functions deploy pubsub_test \
          --gen2 \
          --region asia-northeast1 \
          --runtime python312 \
          --source . \
          --entry-point pubsub_test \
          --trigger-topic YOUR_TOPIC_NAME
